mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_list'), # old class based view before creating tag view (post_list)
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path('newpost/', views.new_post, name='new_post'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

mysite/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from datetime import datetime as dt

class PublishedManager(models.Manager):
    """
    Custom queryset for Post model, to return only published posts
    """
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

# Create your models here.
class Post(models.Model):
    """
    Post model for each blog post
    """

    objects = models.Manager() # default Manager - required when customising Managers
    published = PublishedManager() # custom Manager

    # tags field
    tags = TaggableManager()

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug,
        ])

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'{self.name}, {dt.strftime(self.updated, format="%d %B, %Y")}: {self.body}'

mysite/blog/forms.py
from django import forms
from .models import Comment

class NewPostForm(forms.Form):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = forms.CharField(max_length=250)
    slug = forms.SlugField(required=True)
    author = forms.IntegerField(required=True)
    body = forms.CharField(required=True)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.auth.models import User
from django.views.generic import ListView
from django.db.models import Count
from django.urls import reverse
from taggit.models import Tag
from .models import Post, Comment
from .forms import NewPostForm, CommentForm, SearchForm

# Create your views here.


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    """
    View that shows individual post
    """
    # fetch posts
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    # fetch comments
    comments = post.comments.filter(active=True)
    # initiate new_comment variable for use when creating a new comment
    new_comment = None
    # posting new comment logic
    if request.method == 'POST':
        # ascertain form is valid
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # create comment and assign post foreign key then save
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            # clear form for refresh
            comment_form = CommentForm()
    else:
        # GET request (page load)
        # instantiate blank comment form
        comment_form = CommentForm()
    # list of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
    })


def new_post(request):
    """
    Form to add a new post
    NOTE: This form is for dev use only
    TODO: productionise
    """
    # if post request then get form, validate and save
    if request.method == 'POST':
        # get form contents from posted page
        form = NewPostForm(request.POST)
        # ensure form is valid
        if form.is_valid():
            # gets form values from posted form
            form_cleaned = form.cleaned_data
            # gets user details from id provided in form
            user_obj = get_object_or_404(User, pk=int(form_cleaned['author']))
            # creates new post object
            Post.objects.create(
                title=form_cleaned['title'],
                slug=form_cleaned['slug'],
                author=user_obj,
                body=form_cleaned['body'],
                status='published',
            )
            return HttpResponseRedirect(reverse('blog:post_list'))
    else:
        form = NewPostForm()
    return render(request, 'blog/post/newpost.html', {'form': form})


def post_list(request, tag_slug=None):
    # all published objects
    object_list = Post.published.all()
    # instantiate tag variable
    tag = None
    # if tag slug provided in url then filter for it
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    # create pagination
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not int then return first page
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts, 'page': page, 'tag': tag})

def post_search(request):
    # instantiate form
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        # if get then take params from URL and validate form
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # create search vector that returns weighted results across title and body
            search_vector = SearchVector('title', 'body') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
              search=search_vector,
              rank=SearchRank(search_vector, search_query)
          ).filter(rank__gte=0.3).order_by('-rank')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|markdown }}

  <h2>Similar posts</h2>
{% for post in similar_posts %}
  <p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </p>
{% empty %}
  There are no similar posts yet.
{% endfor %}

{% with comments.count as total_comments %}
<h1>{{ total_comments }} comment{{ total_comments|pluralize }}</h1>
{% endwith %}

{% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|markdown }}
  </div>
{% endfor %}

{% if new_comment %}
  <h2>Your comment has been added.</h2>
{% else %}
  <h2>Add a new comment</h2>
  <form method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
  </form>
{% endif %}

{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
  <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
    Tags:
    {% for tag in post.tags.all %}
      <a href="{% url "blog:post_list_by_tag" tag.slug %}">
        {{ tag.name }}
      </a>
      {% if not forloop.last %}, {% endif %}
    {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown |truncatewords:15 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/newpost.html
{% extends 'blog/base.html' %}
{% block content %}
<form method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Submit"></input>
</form>
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}